// Code generated by github.com/DeedleFake/migrate. DO NOT EDIT.

package migrations

import (
	"context"
	"database/sql"
	"fmt"

	"github.com/DeedleFake/migrate"
)

var funcs = map[string]migrate.MigrationFunc{
	"1": Migrate1,
	"2": Migrate2,
	"3": Migrate3,
}

// Names returns the names of every defined migration.
func Names() []string {
	return []string{
		"1",
		"2",
		"3",
	}
}

// Apply applies the named migrations to the given database.
func Apply(ctx context.Context, db *sql.DB, migrations ...string) error {
	plan, err := migrate.Plan(funcs)
	if err != nil {
		return fmt.Errorf("plan migrations: %w", err)
	}

	err = plan.Run(ctx, db)
	if err != nil {
		return fmt.Errorf("run migrations: %w", err)
	}

	panic("Not implemented.")
}
